[2024-12-20 15:25:58] Bridge validation failed: GET request failed: HTTPConnectionPool(host='none', port=80): Max retries exceeded with url: /api/None/config (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x1068d0380>: Failed to resolve 'none' ([Errno 8] nodename nor servname provided, or not known)"))
[2024-12-20 15:26:02] Bridge validation failed: GET request failed: HTTPConnectionPool(host='none', port=80): Max retries exceeded with url: /api/None/config (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x105260890>: Failed to resolve 'none' ([Errno 8] nodename nor servname provided, or not known)"))
[2024-12-20 15:29:22] Bridge validation failed: argument of type 'coroutine' is not iterable
